Refactor loading with useQuery and adopt formik for form data
canonical/sdcore-nms pull request #148
Opened 2023-10-18 17:06 UTC by edlerd

# Description

* added useQuery dependency for easier loading of data
* adjusted all data loading to useQuery instead of useEffect
* added formik dependency for easier form handling
* added yup dependency for easier form validation
* adjusted all forms to use formik
* design: added consistent loading states to pages
* design: adjusted margin of buttons
* design: adjusted headings to be h1 / h2 and render a bit smaller
* design: removed chip from the subscribers page and add the number of items to the headings
* started using ConfirmationButton component where it simplifies code
* started using ActionButton to make loading of submitted forms visible

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2023-10-19 18:58 UTC, gruyaume approved these changes

2023-10-19 20:01 UTC, gruyaume requested changes
Commits need to be signed to merge this PR

2023-10-19 20:01 UTC, gruyaume commented on components/CreateNetworkSliceModal.tsx
> +          help="Mobile Country Code value of HPLMN"
Refering to HPLMN, I'd try to avoid introducing new accronyms unless we really have to. `Mobile Country Code` should be enough.

2023-10-20 07:54 UTC, edlerd commented on components/CreateNetworkSliceModal.tsx
> +          help="Mobile Country Code value of HPLMN"
simplified the help texts

2023-10-20 11:42 UTC, gruyaume approved these changes

2023-10-20 11:43 UTC, merged