fix: NMS crash when GNBs config file is missing
canonical/sdcore-nms pull request #173
Opened 2023-11-21 15:44 UTC by patriciareinoso

# Description

This PR fixes a NMS crash on Network Slice creation.
The crash happened when GNBs config file was missing or did not contain any GNB.
The error provoke and infinite loop of rendering. The problem was fixed using React Effects.

The same problem was identified and fixed for the UPFs config file. 

In case the config files are missing or there are no GNBs or UPFs. An error message is shown as:
![image](https://github.com/canonical/sdcore-nms/assets/10354025/ad877a92-35bf-4b37-b017-072520bf8d49)

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-11-21 18:52 UTC, gruyaume requested changes

2023-11-21 18:52 UTC, gruyaume commented on components/CreateNetworkSliceModal.tsx
Please fix the PR title

2023-11-21 18:52 UTC, gruyaume commented on components/CreateNetworkSliceModal.tsx
> +      if (!isUpfLoading && upfList.length === 0) {
I'm not sure we should refrain from showing the UI if there is no UPF's in the list, I think having a list of len 0 is fine. What we want to avoid is cases where the upf config file is simply not set

2023-11-22 12:59 UTC, patriciareinoso commented on components/CreateNetworkSliceModal.tsx
> +      if (!isUpfLoading && upfList.length === 0) {
My modifications only prevent the infinite loop re rendering. I did not change the behavior.
In case there are no UPFs or GNBs on the lists a error message is shown in the modal. 
![image](https://github.com/canonical/sdcore-nms/assets/10354025/9f04d1f5-9bee-4491-ab85-c9c58bb2e184)

2023-11-22 13:05 UTC, patriciareinoso commented on components/CreateNetworkSliceModal.tsx
> +      if (!isUpfLoading && upfList.length === 0) {
Not showing the UI when the config files are missing is not implemented here.

2023-11-22 13:06 UTC, gruyaume approved these changes

2023-11-22 13:28 UTC, merged