feat: Prevent user from deleting a device group that contains subscribers
canonical/sdcore-nms pull request #246
Opened 2023-12-11 17:34 UTC by patriciareinoso

# Description

We won't allow the user to remove a Device Group that contains subscribers.
The following modal is shown when the user tries to removed a non empty DG.

![image](https://github.com/canonical/sdcore-nms/assets/10354025/77bf04e3-6767-49aa-9a01-396cfa64d335)

If we try to remove an empty DG there is no change:

![image](https://github.com/canonical/sdcore-nms/assets/10354025/065e13e8-6f6a-46e4-922e-d464e7547251)

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-12-11 17:37 UTC, gruyaume requested changes

2023-12-11 17:37 UTC, gruyaume commented on components/NetworkSliceGroups.tsx
> +              confirmButtonLabel: "Aceptar",
Acceptar?

2023-12-14 11:54 UTC, patriciareinoso commented on components/NetworkSliceGroups.tsx
> +          <ConfirmationButton
The confirmation button automatically deals with toggling. I removed the buttons from the pop up modal so now it looks better. 
I tried to use a button that toggles a notification but I needed to find a place to show the notification and it was harder to pass significant information. 
what do you think?

2023-12-15 13:34 UTC, gruyaume approved these changes

2023-12-15 13:38 UTC, merged