feat: Adding device group edition feature
canonical/sdcore-nms pull request #335
Opened 2024-02-02 11:02 UTC by Gmerold

# Description

Adds possibility of editing existing device groups.
Device group edition modal uses the same layout as the creation modal. 
Validation is the same. 
It is not possible to edit device group name.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-02-02 14:02 UTC, ghislainbourgeois commented on components/NetworkSliceGroups.tsx
> +                        style={{ color: "#666" }}
Shouldn't those things go in the stylesheet?

2024-02-02 14:12 UTC, Gmerold commented on components/NetworkSliceGroups.tsx
> +                        style={{ color: "#666" }}
Honestly, I copied this from the existing `getDeleteButton` :D I have no idea about frontend programming, but I can look into it ;)

2024-02-02 16:48 UTC, patriciareinoso requested changes

2024-02-02 16:48 UTC, patriciareinoso commented on utils/editDeviceGroup.tsx
> +  const deviceGroupData = {
In the `device-group` there is a field called `imsis` that stores the associated `subscribers` by posting a complete hardcoded new object I think this field will be reinitialized to `null`
I had this problem with the network slices and the list of device groups so I am getting the network slice, setting the new fields to the object and re POST ing it again

2024-02-02 16:48 UTC, patriciareinoso commented on components/DeviceGroupModal.tsx
> +  }
could be a ternary expression
` return deviceGroupName ? "Save Changes" : "Create"` 
unless you think is more readable the way it is

2024-02-02 16:48 UTC, patriciareinoso commented on components/DeviceGroupModal.tsx
> +    throw new Error("Either Network Slice name or Device Group must be specified.")
If this error is thrown would the whole app crash ? 

you can use `setApiError` to show an error in the modal to the user. 
but at the end this error does not depend on the user (?)  so I don't know if it would make sense

2024-02-05 10:40 UTC, Gmerold commented on components/NetworkSliceGroups.tsx
> +                        style={{ color: "#666" }}
Moved to the stylesheet.

2024-02-05 10:40 UTC, Gmerold commented on utils/editDeviceGroup.tsx
> +  const deviceGroupData = {
Good catch :) Fixed.

2024-02-05 10:41 UTC, Gmerold commented on components/DeviceGroupModal.tsx
> +  }
:+1:

2024-02-05 11:24 UTC, Gmerold commented on components/DeviceGroupModal.tsx
> +    throw new Error("Either Network Slice name or Device Group must be specified.")
Can't use `setApiError` here. Instead I added a simple Modal to display the error. What do you think?
![image](https://github.com/canonical/sdcore-nms/assets/42570669/28412b98-2361-404f-9944-4e73e870cc8d)

2024-02-05 16:03 UTC, patriciareinoso approved these changes

2024-02-06 09:12 UTC, merged