feat: add webui backend to rock
canonical/sdcore-nms pull request #621
Opened 2024-07-04 15:11 UTC by patriciareinoso

# WIP. DO NOT MERGE

# Description

The Rock container image for the NMS should contain both the Next.JS frontend (NMS) and backend components (WebUI). 

This PR:
- Build the frontend
- Copy the static files over to the `webconsole/ui/frontend_files` directory
- Build the backend with the ui go build tag.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-07-04 15:11 UTC, patriciareinoso commented on rockcraft.yaml
>  services:
can I remove the service just like the other rocks?

2024-07-04 15:12 UTC, patriciareinoso commented on rockcraft.yaml
> +    source-commit: 93f675baa7eb5f5df37e4013cf4cda0beeba5d84
replace commit by tag

2024-07-04 15:12 UTC, patriciareinoso commented on rockcraft.yaml
> +    source-commit: 5dd01d6c484331d4134cd0d11c60358f4cb160f3
replace commit by 
`source: . ` 
as before

2024-07-04 15:13 UTC, patriciareinoso commented on rockcraft.yaml
>    amd64:
What version to use?

2024-07-16 13:19 UTC, patriciareinoso commented on rockcraft.yaml
> +  webui:
```suggestion
  nms:
```

2024-08-02 12:14 UTC, gruyaume requested changes

2024-08-02 12:14 UTC, gruyaume commented on rockcraft.yaml
> +    source: https://github.com/patriciareinoso/webconsole.git
We should probably wait for this change to be tagged before merging. Gab should be able to create the new tag.

2024-08-02 12:14 UTC, gruyaume commented on .github/workflows/integration_tests.yaml
Why get rid of the integration tests?

2024-08-07 12:06 UTC, gruyaume approved these changes

2024-08-07 12:27 UTC, merged