feat: makefile for automating builds and deployments for dev environments
canonical/sdcore-nms pull request #646
Opened 2024-10-09 14:11 UTC by kayra1

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-10-22 10:13 UTC, patriciareinoso requested changes

2024-10-22 10:13 UTC, patriciareinoso commented on CONTRIBUTING.md
> +There are 2 targets for building: the `webconsole` binary and the `sdcore-nsm.rock` OCI image. The artifacts
```suggestion
There are 2 targets for building: the `webconsole` binary and the `sdcore-nms.rock` OCI image. The artifacts
```

2024-10-22 10:36 UTC, kayra1 commented on examples/config/webuicfg.yaml
> +configuration:
This PR does not have the authorization functionality in the frontend, so I decided to add that in #650 .

2024-10-22 11:52 UTC, patriciareinoso requested changes

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +### Webconsole
```suggestion
### Webconsole binary
```

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +The `make webconsole` target is responsible for producing the binary that serves the NMS frontend. For this process:
The `For this process:` sentence sounds like if the user needs to run all of these steps.

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
You could add that the binary generated cannot be run because is missing the config file.

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +1. clone the `omec-project/webconsole` repository into `build/webconsole-src`
all the elements on the numbered lists below start with uppercase. These should start with uppercase as well

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +### `make hotswap`
just tested it and it's nice :)

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +This target will take the webconsole binary, place it in the `nms` container inside the LXC VM, and restart the pebble service.
You could add that this is useful to test local changes on the front end without having to redeploy everything

2024-10-22 11:52 UTC, patriciareinoso commented on CONTRIBUTING.md
> +The `make rock` target can modify this build process by directly using the `build/webconsole-src` directory. This allows you to use a local version of webconsole in the OCI image instead of having to
```suggestion
The `make rock` target modifies this build process by directly using the `build/webconsole-src` directory. This allows you to use a local version of webconsole in the OCI image instead of having to pull from the specified tag in `rockcraft.yaml`. This is useful if you want to test changes to the backend rather than the frontend. The process is:
```

2024-10-22 11:52 UTC, patriciareinoso commented on Makefile
> +	-rockcraft pack
I was worried about ending up with a modified rockcraft.yaml file. But the `-` solves this. Nice :+1:

2024-10-22 11:52 UTC, patriciareinoso commented on Makefile
> +		-e WEBUI_ENDPOINT=localhost:5000 \
is there a way to set up the IP of the machine here? Otherwise I think that the swagger does not work

2024-10-22 12:36 UTC, Gmerold commented on CONTRIBUTING.md
> +### `make webconsole`
```
rm -rf build/nms-static
mv out build/nms-static
rm -rf build/webconsole-src/ui/frontend_files/*
cp -R build/nms-static/* build/webconsole-src/ui/frontend_files
cp: target 'build/webconsole-src/ui/frontend_files' is not a directory
make: *** [Makefile:86: artifacts/webconsole] Error 1
```
Is this expected? :D

2024-10-22 13:36 UTC, gatici commented
I was testing and `make rock` has failed. I attached the full logs here: https://pastebin.ubuntu.com/p/TvWn6HKNrk/
```
make rock
make: building oci image with a local version of webconsole
mv rockcraft.yaml rockcraft_default.yaml
sed "s~source-type.*~~; s~source-tag.*~~; s~source: https.*~source: .\/build/webconsole-src~" rockcraft_default.yaml > rockcraft.yaml
rockcraft pack
'override-build' in part 'nms' failed with code 1.                                                                                                                                                                             
Recommended resolution: Review the scriptlet and make sure it's correct.                                                                                                                                                       
Failed to execute rockcraft in instance.                                                                                                                                                                                       
Full execution log: '/home/gatici/.local/state/rockcraft/log/rockcraft-20241022-162747.266520.log'                                                                                                                             
make: [Makefile:95: artifacts/sdcore-nms.rock] Error 1 (ignored)
mv rockcraft_default.yaml rockcraft.yaml
Built rock with local webconsole
``

2024-10-22 14:00 UTC, kayra1 commented on CONTRIBUTING.md
> +The `make webconsole` target is responsible for producing the binary that serves the NMS frontend. For this process:
Updated to say "Once run, it will:"

2024-10-22 14:00 UTC, kayra1 commented on CONTRIBUTING.md
Added it below.

2024-10-22 14:00 UTC, kayra1 commented on CONTRIBUTING.md
> +1. clone the `omec-project/webconsole` repository into `build/webconsole-src`
done

2024-10-22 14:00 UTC, kayra1 commented on CONTRIBUTING.md
> +### `make hotswap`
:D

2024-10-22 14:00 UTC, kayra1 commented on CONTRIBUTING.md
> +This target will take the webconsole binary, place it in the `nms` container inside the LXC VM, and restart the pebble service.
added

2024-10-22 14:31 UTC, kayra1 commented on CONTRIBUTING.md
> +### `make webconsole`
it is expected if git clone fails to download the repo :D

2024-10-23 06:17 UTC, Gmerold approved these changes
It worked :D
Added some minor comments, but other than that it's really cool.

2024-10-23 06:17 UTC, Gmerold commented on CONTRIBUTING.md
> +After the process is done, from your host machine you can run `lxc list`, and use the IP address to connect to both mongodb and NMS. The port for NMS is `:5000` and the port for mongodb is `:27017`.
How about we move this to `### make deploy`?
I was actually expecting something that would tell me how to access the thing I just deployed and was a bit confused not finding it.

2024-10-23 06:17 UTC, Gmerold commented on CONTRIBUTING.md
> +for them are stored in the `/artifacts` folder. Any files used in the build process is stored in the `/build` folder.
```suggestion
for them are stored in the `/artifacts` folder. Any files used in the build process are stored in the `/build` folder.
```

2024-10-23 06:17 UTC, Gmerold commented on CONTRIBUTING.md
> +The `make webconsole` target is responsible for producing the binary that serves the NMS frontend. Once run, it will:
```suggestion
The `make webconsole` target is responsible for producing the binary that serves the NMS frontend. Once ran, it will:
```

2024-10-23 06:38 UTC, kayra1 commented on CONTRIBUTING.md
> +The `make webconsole` target is responsible for producing the binary that serves the NMS frontend. Once run, it will:
It is either "Once it runs" or "Once run", Once ran is actually [wrong](https://quillbot.com/grammar-check).

2024-10-23 06:40 UTC, kayra1 commented on CONTRIBUTING.md
> +After the process is done, from your host machine you can run `lxc list`, and use the IP address to connect to both mongodb and NMS. The port for NMS is `:5000` and the port for mongodb is `:27017`.
moved.

2024-10-23 06:54 UTC, kayra1 commented on Makefile
> +		-e WEBUI_ENDPOINT=localhost:5000 \
I can echo the IP address of the vm if that would be helpful?

2024-10-23 09:16 UTC, patriciareinoso commented on Makefile
> +		-e WEBUI_ENDPOINT=localhost:5000 \
hmm you would need to use the lxc list command to echo it? 
the thing is that WEBUI_ENDPOINT must point to where the service is running so it should be the VM IP

2024-10-23 09:30 UTC, gatici approved these changes
Good job.Thank you.

`make rock` works for me if I remove the `npm ci` from the `rockcraft.yaml`. 
And it worked as expected. Do we really need `npm ci` ? Maybe it is not necessary.
Other than that LGTM.

2024-10-23 09:30 UTC, gatici commented on Makefile
> +		-e WEBUI_ENDPOINT=localhost:5000 \
Here shows how to set IPs for LXD VM's. https://discuss.linuxcontainers.org/t/using-static-ips-with-lxd/1291/6

2024-10-23 12:53 UTC, kayra1 commented on Makefile
> +		-e WEBUI_ENDPOINT=localhost:5000 \
for this the VM needs to be stopped, and restarted after, which just introduces more wait time to the makefile. I think just adding a echo "here's the VM: lxc info nms" is the best option since it's less prone to errors and more flexible.

2024-10-25 11:43 UTC, patriciareinoso approved these changes

2024-10-28 15:34 UTC, merged