feat: authentication flow
canonical/sdcore-nms pull request #659
Opened 2024-11-12 15:58 UTC by kayra1

# Description

This PR introduces authentication to the frontend of NMS. The user will either be redirected to the initialize endpoint or login endpoint if they haven't logged in. Admin users have access to the users panel, which allows them to create, delete or update the password of existing user accounts.

For testing, please use the webconsole version that includes the authentication changes.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-11-12 17:41 UTC, gruyaume requested changes
As soon as I initialize the admin user (or try to log in) I get redirected to the login page. This is by cloning your fork and going through the CONTRIBUTING.md guidelines. 

I believe I'm properly logged in but something redirects me to the login page regardless.

![image](https://github.com/user-attachments/assets/7131c3fd-5aa4-4e7f-ab45-ac16c7b661c6)

2024-11-12 18:11 UTC, gruyaume commented
> As soon as I initialize the admin user (or try to log in) I get redirected to the login page. This is by cloning your fork and going through the CONTRIBUTING.md guidelines.
> 
> I believe I'm properly logged in but something redirects me to the login page regardless.
> 
> ![image](https://private-user-images.githubusercontent.com/18486508/385397563-7131c3fd-5aa4-4e7f-ab45-ac16c7b661c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzUzNDksIm5iZiI6MTczMTQzNTA0OSwicGF0aCI6Ii8xODQ4NjUwOC8zODUzOTc1NjMtNzEzMWMzZmQtNWFhNC00ZTdmLWFiNDUtYWMxNmM3YjY2MWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE4MTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTk2OWVmMDg0NWE1YjI1ZWNiNDdhMWI2NzRkOWE2MjFkZmIwYmEwZWQzMjJjNTlmYTNmMGUyYTkzYmE5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7KOgvdY2Hcs_LlDWgVJqn8yoJgS2nRxyi_26fCmbSI4)

Actually, it seems like the token does not get added to my cookies.

2024-11-12 18:13 UTC, gruyaume commented
> > As soon as I initialize the admin user (or try to log in) I get redirected to the login page. This is by cloning your fork and going through the CONTRIBUTING.md guidelines.
> > I believe I'm properly logged in but something redirects me to the login page regardless.
> > ![image](https://private-user-images.githubusercontent.com/18486508/385397563-7131c3fd-5aa4-4e7f-ab45-ac16c7b661c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzUzNDksIm5iZiI6MTczMTQzNTA0OSwicGF0aCI6Ii8xODQ4NjUwOC8zODUzOTc1NjMtNzEzMWMzZmQtNWFhNC00ZTdmLWFiNDUtYWMxNmM3YjY2MWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE4MTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTk2OWVmMDg0NWE1YjI1ZWNiNDdhMWI2NzRkOWE2MjFkZmIwYmEwZWQzMjJjNTlmYTNmMGUyYTkzYmE5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7KOgvdY2Hcs_LlDWgVJqn8yoJgS2nRxyi_26fCmbSI4)
> 
> Actually, it seems like the token does not get added to my cookies.

This is caused by the `secure` option when setting the cookie. It is set to True but the CONTRIBUTING.md and make file lead to an environment that does not use https.

2024-11-12 18:18 UTC, gruyaume requested changes

2024-11-12 18:18 UTC, gruyaume commented on utils/auth.tsx
> +    }, [token]);
React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array

2024-11-12 18:18 UTC, gruyaume commented on app/(nms)/users/page.tsx
The action button is misaligned:

![image](https://github.com/user-attachments/assets/14710a66-82ea-4e43-a93a-678cc97507d4)

2024-11-12 18:18 UTC, gruyaume commented on app/(nms)/users/modals.tsx
When I create a used that already exists, I am not informed that the operation didn't succeed, we should likely add a error notification here.

![image](https://github.com/user-attachments/assets/a99ff5c3-1943-4549-95ff-56a911ef2ee9)

2024-11-12 18:18 UTC, gruyaume commented on app/(nms)/users/page.tsx
> +      <PageHeader title={`NMS Accounts (${users.length})`}>
```suggestion
      <PageHeader title={`Users (${users.length})`}>
```

We are interchangibly using "accounts" and "users", let's make sure to always use the same word when we identify this concept.

2024-11-13 09:56 UTC, kayra1 commented
> This is caused by the `secure` option when setting the cookie. It is set to True but the CONTRIBUTING.md and make file lead to an environment that does not use https.

The code to add the token to the cookies is identical to the one in Notary, and I can't recreate this issue locally even in a fresh VM. @patriciareinoso had the same issue. If it's possible I would appreciate hopping on a quick call to debug.

2024-11-13 10:27 UTC, kayra1 commented
> This is caused by the `secure` option when setting the cookie. It is set to True but the CONTRIBUTING.md and make file lead to an environment that does not use https.

i usually have an ssh tunnel into the environment, and localhost is excepted from the `Secure` cookie. I've removed the secure option, we can reintroduce it when making the change to move to https.

2024-11-13 12:35 UTC, kayra1 commented on app/(nms)/users/page.tsx
> +      <PageHeader title={`NMS Accounts (${users.length})`}>
Updated

2024-11-13 13:33 UTC, kayra1 commented on app/(nms)/users/page.tsx
this took me 3 hours

2024-11-13 13:48 UTC, kayra1 commented on utils/auth.tsx
> +import { createContext, useContext, useState, useEffect, Dispatch, SetStateAction } from 'react';
gone

2024-11-13 14:10 UTC, kayra1 commented on app/(nms)/users/modals.tsx
done

2024-11-15 12:02 UTC, gruyaume approved these changes

2024-11-15 14:22 UTC, patriciareinoso requested changes
After creating a network slice or a subscriber, I need to refresh the page to see it on the list. But this only happens with the first one. I think this was raised as an issue that was closed some time agou because it disappeared but now seems to be back. @gruyaume

2024-11-15 14:35 UTC, patriciareinoso requested changes
If I log in as a not admin user and I try to reach <ip>:5000/users on the browser address even if the `Users` button does not exist. It says loading and keep trying to the the users endpoint (http://10.97.137.188:5000/config/v1/account). Could it be possible to block the user? show something like `page does not exist` ? 

![image](https://github.com/user-attachments/assets/8a6c5630-11a8-420b-93b1-71d8d14ffffa)

2024-11-18 10:53 UTC, kayra1 commented
> If I log in as a not admin user and I try to reach :5000/users on the browser address even if the `Users` button does not exist. It says loading and keeps trying to reach the users endpoint (http://10.97.137.188:5000/config/v1/account). Could it be possible to block the user? show something like `page does not exist` ?
> 
> ![image](https://private-user-images.githubusercontent.com/10354025/386640040-8a6c5630-11a8-420b-93b1-71d8d14ffffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjU3OTgsIm5iZiI6MTczMTkyNTQ5OCwicGF0aCI6Ii8xMDM1NDAyNS8zODY2NDAwNDAtOGE2YzU2MzAtMTFhOC00MjBiLTkzYjEtNzFkOGQxNGZmZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEwMjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjc1ZTIwNTQwZGI2YjY0NDQyNWY2YjllM2NiMTRjNmViOWIzNWQ4NWVhZGNhNTNmZDg1Y2Q3MDRiYTQ5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zzI43cvPxt53vBUJtFfx0sOYqwpgN4gNBjKZmjVpO0I)

how about redirecting to "/" for now? I want to pay special attention to having a 404 page, and preferably would like to do that after converting everything to canonical react components.

2024-11-18 11:12 UTC, patriciareinoso commented
> > If I log in as a not admin user and I try to reach :5000/users on the browser address even if the `Users` button does not exist. It says loading and keeps trying to reach the users endpoint (http://10.97.137.188:5000/config/v1/account). Could it be possible to block the user? show something like `page does not exist` ?
> > ![image](https://private-user-images.githubusercontent.com/10354025/386640040-8a6c5630-11a8-420b-93b1-71d8d14ffffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjU3OTgsIm5iZiI6MTczMTkyNTQ5OCwicGF0aCI6Ii8xMDM1NDAyNS8zODY2NDAwNDAtOGE2YzU2MzAtMTFhOC00MjBiLTkzYjEtNzFkOGQxNGZmZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEwMjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjc1ZTIwNTQwZGI2YjY0NDQyNWY2YjllM2NiMTRjNmViOWIzNWQ4NWVhZGNhNTNmZDg1Y2Q3MDRiYTQ5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zzI43cvPxt53vBUJtFfx0sOYqwpgN4gNBjKZmjVpO0I)
> 
> how about redirecting to "/" for now? I want to pay special attention to having a 404 page, and preferably would like to do that after converting everything to canonical react components.

sure, that works

2024-11-18 15:05 UTC, patriciareinoso commented
> After creating a network slice or a subscriber, I need to refresh the page to see it on the list. But this only happens with the first one. I think this was raised as an issue that was closed some time agou because it disappeared but now seems to be back. @gruyaume

as discussed, this will be tracked in a task (TELCO-1477) since it's not related to authentication.

2024-11-18 15:06 UTC, patriciareinoso approved these changes

2024-11-19 15:28 UTC, merged