[feat] Adds network slice composition
canonical/sdcore-nms pull request #90
Opened 2023-09-15 02:35 UTC by gruyaume

# Description

Adds network slice composition

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-09-15 15:25 UTC, ghislainbourgeois reviewed
Overall this looks OK. I would get someone more well-versed in frontend development to take a look at the CodeQL warnings to ensure this is well handled.

My understanding is that the operator for this will update the configuration files for UPFs and gNodeBs based on the relations, right?

2023-09-25 20:47 UTC, ghislainbourgeois requested changes

2023-09-25 20:47 UTC, ghislainbourgeois commented on components/CreateSubscriberModal.tsx
> +
This reads a bit weird having this be a constant, shouldn't this be a function? When is it evaluated?

2023-09-25 20:47 UTC, ghislainbourgeois commented on components/DeviceGroupModal.tsx
> +  return mtu >= 1200 && mtu <= 65536;
This is a 16 bit field, thus the maximum value is 65535.
```suggestion
  return mtu >= 1200 && mtu <= 65535;
```

2023-09-25 20:47 UTC, ghislainbourgeois commented on components/NetworkSliceModal.tsx
> +    NameValidationError !== null;
Same comment as above

2023-09-25 21:15 UTC, gruyaume commented on components/CreateSubscriberModal.tsx
> +
I'm not 100% sure that the function alternative looks better. Here we'd have:

```
  function isCreateDisabled(
    imsi: string,
    opc: string,
    key: string,
    sequenceNumber: string,
    selectedSlice: string | null,
    deviceGroupOptions: string[],
    IMSIValidationError: string | null,
    OPCValidationError: string | null,
    KeyValidationError: string | null,
  ) {
    return (
      !imsi ||
      !opc ||
      !key ||
      !sequenceNumber ||
      !selectedSlice ||
      deviceGroupOptions.length === 0 ||
      IMSIValidationError !== null ||
      OPCValidationError !== null ||
      KeyValidationError !== null
    );
  }
```
and at evaluation time:

```
<Button
            onClick={handleSave}
            appearance="positive"
            disabled={isCreateDisabled(
              imsi,
              opc,
              key,
              sequenceNumber,
              selectedSlice,
              deviceGroupOptions,
              IMSIValidationError,
              OPCValidationError,
              KeyValidationError,
            )}
            className="u-no-margin--bottom"
          >
            Create
          </Button>
```

2023-09-26 12:28 UTC, saltiyazan commented
I'm testing it in a deployment, will provide my review soon.

2023-09-27 08:51 UTC, saltiyazan commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
```suggestion
docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.2
```
0.2?

2023-09-27 09:00 UTC, saltiyazan commented on utils/deleteSubscriber.tsx
subscriber won't be deleted if the network slice is deleted first. (it will stay there on the ui at least and the delete button won't work.)

2023-09-27 09:06 UTC, saltiyazan commented on README.md
running without `webui` accessibility gives me `Backend not available` error on the nms gui.
Should we consider adding it here?

2023-09-27 09:16 UTC, saltiyazan commented on pages/api/upf.ts
> +        }
should handle the file not existing or having issues? this can be a bit misleading. In the UI it would like there is no `upf`

2023-09-27 09:26 UTC, saltiyazan commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
```suggestion
docker run -it --env UPF_CONFIG_PATH=$UPF_CONFIG_PATH --env GNB_CONFIG_PATH=$GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
```

2023-09-27 09:33 UTC, saltiyazan commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
the upf list was not showing in the gui.
It turned out that the container was not able to access the file on my local system, so I had to add the following option `-v /home/ubuntu/sdcore-nms/examples/upf_config.json:/home/ubuntu/sdcore-nms/examples/upf_config.json`.
I added a comment in the `pages/api/upf.ts` to handle such a case when there is no file and show some kind of error message.

2023-09-27 09:48 UTC, saltiyazan commented on components/DeviceGroupModal.tsx
<img width="662" alt="Screenshot 2023-09-27 at 13 48 10" src="https://github.com/canonical/sdcore-nms/assets/26838825/399d3a31-df29-463f-a2dd-869f58eb2e35">

This is what I see after creating device groups, and I could create 2 device groups with the same name in the same network slice.

2023-09-27 11:42 UTC, gruyaume commented on README.md
Done, this should be clearer now

2023-09-27 12:12 UTC, gruyaume commented on pages/api/upf.ts
> +        }
I improved this, now the modal will have an error in it telling we can't retrieve the upf list and the server will log an error as well. This should help the user figure out what to do.

2023-09-27 12:12 UTC, gruyaume commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
There is an error message for this now

2023-09-27 12:28 UTC, gruyaume commented on utils/deleteSubscriber.tsx
Do you mind re-testing this? I'm not seeing this error, I know there has been some changes in the webui api code, this could have been related to this.

2023-09-27 12:30 UTC, gruyaume commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
The current doc is ok, docker supports using variables in the local environment

2023-09-27 18:01 UTC, ghislainbourgeois commented on components/CreateSubscriberModal.tsx
> +
Ok, so this is used as a macro and replaced as is in the outputted code. In that case I agree that the current way is better.

2023-09-27 18:03 UTC, ghislainbourgeois commented on components/DeviceGroupModal.tsx
The 2 device groups with the same name I think were due to an issue in `webui` that should be fixed now. Are you able to re-test with a fresh install?

2023-09-27 18:08 UTC, ghislainbourgeois requested changes

2023-09-27 18:08 UTC, ghislainbourgeois commented on README.md
>  docker pull ghcr.io/canonical/sdcore-nms:0.1
```suggestion
docker pull ghcr.io/canonical/sdcore-nms:0.2
```

2023-09-27 18:14 UTC, ghislainbourgeois requested changes

2023-09-27 18:14 UTC, ghislainbourgeois commented on examples/upf_config.json
> +      "hostname": "upf",
This would make this example file usable with our default deployment
```suggestion
      "hostname": "upf-external",
```

2023-09-27 18:17 UTC, ghislainbourgeois commented on components/DeviceGroupModal.tsx
I tried it myself on a fresh install, and it looks like it creates 2 identical device groups, but if I check directly with `curl`, only a single device group is really created. This is definitely a bug in the NMS.

2023-09-27 18:20 UTC, ghislainbourgeois commented on components/DeviceGroupModal.tsx
Trying to add a subscriber, it also shows the 2 identical device groups, but the first one does not work and pops an error.

2023-09-28 10:53 UTC, saltiyazan commented on components/DeviceGroupModal.tsx
Data is showing now except for the slice name
![Screenshot 2023-09-28 at 14 52 41](https://github.com/canonical/sdcore-nms/assets/26838825/99f2bcf7-7acb-42b5-bd58-f32b86a9cdbe)

2023-09-28 11:32 UTC, saltiyazan commented on utils/deleteSubscriber.tsx
I don't know what was causing the issue (maybe the change in webui). But retested and now the subscriber is deleted if the network slice is deleted.

2023-09-28 11:33 UTC, saltiyazan commented on README.md
> +docker run -it --env UPF_CONFIG_PATH --env GNB_CONFIG_PATH ghcr.io/canonical/sdcore-nms:0.1
It didn't work for me, but if it did for you then that's fine, I'll resolve it :)

2023-09-29 06:44 UTC, saltiyazan approved these changes

2023-09-29 11:43 UTC, merged